### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [aripp2/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [ ] I broke down larger processes into smaller layers.
> I'm a little confused about some of the substeps. It looks like `drive` is a substep of `arrive at restaurant`. It's also a little confusing to put steps like unlocking the car and putting on seatbelt under the `Order` step.
- [x] I added and committed my changes with a properly formatted commit message starting with a verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The three attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The three methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [ ] The three attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [ ] The three methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [ ] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Assessment Results
- [ ] Technical Ready
- [x] Pending
> We want to see two things:
> 1. Try the top down design portion again. Make a separate file called `top_down_take_two.md` and use the scenario "Applying for a job". Make sure that every substep is a part of its parent step. If it's not, try to identify a different step that you may have forgotten to break down. Add and commit those changes, then push back up to GitHub and let us know when you're ready for us to check it. 
> 2. With classes and objects, you're on the right path, but your objects should be types of the class. For example, your Class 2 defines `Table`. That means that your attributes should all have to do with **one** specific type of table instead of attributes that are data about multiple tables (`tables_being_used` applies to many tables, as does `total_tables`). Better attributes might be things like `number_of_legs` or `material` or `number_of_seats` since those pertain to a singular instance of `Table`. Make two more files (`class_3.txt` and `class_3_example_object.txt`) and identify one more class from a restaurant and one example of an object of that class. Add and commit those changes, then push back up to GitHub and let us know when you're ready for us to check it. 
- [ ] Not Technical Ready
